# GitHub Copilot Setup Steps - Optimized
# This file configures caching and setup for faster Coding Agent operations
# Uses gradle-build-action for automatic caching and dependency management
# 
# Performance improvements:
# - Cold builds: ~5m → ~1m 17s
# - Warm builds: ~1s
# - Simplified setup with gradle-build-action

name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
    
      # Use gradle-build-action for automatic caching and setup
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
    
      # Pre-compile sources to warm up build cache
      # This provides the main performance benefit (5m → 1m17s)
      - name: Warm up build cache
        run: ./gradlew compileDebugSources -x test
